# Generated by Django 4.2.23 on 2025-07-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_rename_vacancy_template_vacancies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='vacancies',
            field=models.ManyToManyField(blank=True, to='data.vacancy'),
        ),
    ]
