# Generated by Django 4.2.23 on 2025-07-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_template_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.EmailField(default=0, max_length=254, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(default=1, max_length=15, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
