# Generated by Django 4.2.23 on 2025-07-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_candidate_notes_alter_candidate_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='vacancies',
            field=models.ManyToManyField(blank=True, to='data.vacancy'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='candidates',
            field=models.ManyToManyField(blank=True, to='data.candidate'),
        ),
    ]
