# Generated by Django 4.2.23 on 2025-07-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_remove_candidate_vacancies_candidate_vacancies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='vacancies',
        ),
        migrations.AddField(
            model_name='candidate',
            name='vacancies',
            field=models.ManyToManyField(blank=True, to='data.vacancy'),
        ),
    ]
