# Generated by Django 4.2.23 on 2025-07-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_remove_candidate_vacancies_candidate_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='templates',
            field=models.ManyToManyField(blank=True, to='data.template'),
        ),
    ]
