# Generated by Django 4.2.23 on 2025-07-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_remove_vacancy_candidates_remove_vacancy_templates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='candidates',
            field=models.ManyToManyField(blank=True, to='data.candidate'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='templates',
            field=models.ManyToManyField(blank=True, to='data.template'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='vacancies',
            field=models.ManyToManyField(blank=True, to='data.vacancy'),
        ),
        migrations.AlterField(
            model_name='template',
            name='vacancies',
            field=models.ManyToManyField(blank=True, to='data.vacancy'),
        ),
    ]
