# Generated by Django 4.2.23 on 2025-07-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_remove_template_vacancies_alter_vacancy_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='tg',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телеграм'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('sent message', 'письмо отправлено'), ('response recieved', 'Ответ получен'), ('contact fixe', 'Контакт закреплен'), ('rejected', 'Отклонен')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
