# Generated by Django 4.2.23 on 2025-07-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_candidate_tg_alter_candidate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('New', 'Новый'), ('Message sent', 'Письмо отправлено'), ('Response recieved', 'Ответ получен'), ('Contact fixe', 'Контакт закреплен'), ('Rejected', 'Отклонен')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
