# Generated by Django 4.2.23 on 2025-08-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_alter_vacancy_description_alter_vacancy_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
