# Generated by Django 4.2.23 on 2025-08-23 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_alter_template_content_alter_template_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
