# Generated by Django 4.2.23 on 2025-08-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        ('data', '0022_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='candidates',
            field=models.ManyToManyField(blank=True, related_name='vacancies', to='candidates.candidate'),
        ),
    ]
