# Generated by Django 4.2.23 on 2025-08-24 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0023_delete_candidate_alter_vacancy_candidates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacancy',
        ),
    ]
