# Generated by Django 4.2.23 on 2025-08-24 05:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birthday', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('tg', models.CharField(blank=True, max_length=100, verbose_name='Телеграм')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Номер телефона')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Резюме')),
                ('status', models.CharField(choices=[('New', 'Новый'), ('Message sent', 'Письмо отправлено'), ('Response recieved', 'Ответ получен'), ('Contact fixe', 'Контакт закреплен'), ('Rejected', 'Отклонен')], default='new', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Кандидат',
                'verbose_name_plural': 'Кандидаты',
            },
        ),
    ]
