# Generated by Django 4.2.23 on 2025-07-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_candidate_status_alter_candidate_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='candidates',
            field=models.ManyToManyField(blank=True, null=True, to='user_profile.candidate'),
        ),
    ]
