# Generated by Django 4.2.23 on 2025-07-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='vacancy',
            new_name='vacancies',
        ),
    ]
