# Generated by Django 4.2.23 on 2025-07-16 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_candidate_vacancies_alter_vacancy_candidates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='vacancies',
        ),
        migrations.AddField(
            model_name='candidate',
            name='vacancies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates_applied', to='user_profile.vacancy'),
        ),
    ]
