# Generated by Django 4.2.23 on 2025-07-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_remove_candidate_vacancies_alter_vacancy_candidates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='vacancies',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='templates',
            field=models.ManyToManyField(blank=True, related_name='vacancies', to='user_profile.template'),
        ),
    ]
