# Generated by Django 4.2.23 on 2025-08-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0019_alter_candidate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
