# Generated by Django 4.2.23 on 2025-08-24 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancy_templates'),
        ('user_profile', '0024_delete_vacancy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
    ]
