# Generated by Django 4.2.23 on 2025-08-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='templates',
            field=models.ManyToManyField(blank=True, related_name='vacancies', to='templates.template'),
        ),
    ]
